import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import IUser from "@/model/User";
import UserItem from "@/components/UserItem";
import BackToHomeButton from "@/components/BackButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [users, setUsers] = useState<IUser[]>([]);

  const fetchUsers = () => {
    fetch("https://jsonplaceholder.typicode.com/users")
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        setUsers(data);
      });
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Exercise 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BackToHomeButton />
        <h2 className={inter.className}>Exercise 1</h2>

        {users.length > 0 &&
          users.map((user) => (
            <UserItem
              key={user.id}
              name={user.name}
              address={user.address}
              company={user.company}
            />
          ))}
      </main>
    </>
  );
}
