import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HolyWally Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/exercise1" className={inter.className}>
          Exercise 1
        </Link>
        <Link href="/exercise2" className={inter.className}>
          Exercise 2
        </Link>
        <Link href="https://gist.github.com/luanccp/ca0abd582ca284d8bf807a203aa5e2fe" target="_blank" className={inter.className}>
          Exercise 3
        </Link>
        <Link href="/exercise4" className={inter.className}>
          Exercise 4
        </Link>
      </main>
    </>
  );
}
