import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HolyWally Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a href="/exercise1" className={inter.className}>
          Exercise 1
        </a>
        <a href="/exercise2" className={inter.className}>
          Exercise 2
        </a>
        <a href="/exercise3" className={inter.className}>
          Exercise 3
        </a>
        <a href="/exercise4" className={inter.className}>
          Exercise 4
        </a>
      </main>
    </>
  );
}
